"""Add identities uploads revisions and collaboration"""

import sqlalchemy as sa
from alembic import op

revision = "e0ccc83238cb"
down_revision = None
branch_labels = None
depends_on = None


# Complexity: O(1) schema creation; all tables are new and empty.
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_access_tokens",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_mcp_access_tokens")),
    )
    op.create_index(op.f("ix_mcp_access_tokens_expires_at"), "mcp_access_tokens", ["expires_at"], unique=False)
    op.create_table(
        "mcp_clients",
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("client_id", name=op.f("pk_mcp_clients")),
    )
    op.create_table(
        "mcp_flows",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_mcp_flows")),
    )
    op.create_index(op.f("ix_mcp_flows_expires_at"), "mcp_flows", ["expires_at"], unique=False)
    op.create_table(
        "mcp_refresh_tokens",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_mcp_refresh_tokens")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("google_sub", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_users_google_sub")),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("current_revision_id", sa.String(length=36), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_artifacts_owner_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint("path", name=op.f("uq_artifacts_path")),
    )
    op.create_table(
        "upload_grants",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("expected_revision_id", sa.String(length=36), nullable=True),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_upload_grants_user_id_users")),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_upload_grants")),
    )
    op.create_index(op.f("ix_upload_grants_expires_at"), "upload_grants", ["expires_at"], unique=False)
    op.create_table(
        "web_sessions",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_web_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_web_sessions")),
    )
    op.create_index(op.f("ix_web_sessions_expires_at"), "web_sessions", ["expires_at"], unique=False)
    op.create_table(
        "revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], name=op.f("fk_revisions_artifact_id_artifacts")),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_revisions_author_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revisions")),
    )
    op.create_index(op.f("ix_revisions_artifact_id"), "revisions", ["artifact_id"], unique=False)
    op.create_table(
        "comment_threads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("revision_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("anchor", sa.JSON(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifacts.id"], name=op.f("fk_comment_threads_artifact_id_artifacts")
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_comment_threads_author_id_users")),
        sa.ForeignKeyConstraint(
            ["revision_id"], ["revisions.id"], name=op.f("fk_comment_threads_revision_id_revisions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment_threads")),
    )
    op.create_index(op.f("ix_comment_threads_artifact_id"), "comment_threads", ["artifact_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_comments_author_id_users")),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["comment_threads.id"], name=op.f("fk_comments_thread_id_comment_threads")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(op.f("ix_comments_thread_id"), "comments", ["thread_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("recipient_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=False),
        sa.Column("comment_id", sa.String(length=36), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_notifications_actor_id_users")),
        sa.ForeignKeyConstraint(["comment_id"], ["comments.id"], name=op.f("fk_notifications_comment_id_comments")),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], name=op.f("fk_notifications_recipient_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index("ix_notifications_recipient_created", "notifications", ["recipient_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_recipient_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_comments_thread_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_comment_threads_artifact_id"), table_name="comment_threads")
    op.drop_table("comment_threads")
    op.drop_index(op.f("ix_revisions_artifact_id"), table_name="revisions")
    op.drop_table("revisions")
    op.drop_index(op.f("ix_web_sessions_expires_at"), table_name="web_sessions")
    op.drop_table("web_sessions")
    op.drop_index(op.f("ix_upload_grants_expires_at"), table_name="upload_grants")
    op.drop_table("upload_grants")
    op.drop_table("artifacts")
    op.drop_table("users")
    op.drop_table("mcp_refresh_tokens")
    op.drop_index(op.f("ix_mcp_flows_expires_at"), table_name="mcp_flows")
    op.drop_table("mcp_flows")
    op.drop_table("mcp_clients")
    op.drop_index(op.f("ix_mcp_access_tokens_expires_at"), table_name="mcp_access_tokens")
    op.drop_table("mcp_access_tokens")
    # ### end Alembic commands ###
